build:
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

complexity:
  active: true
  NamedArguments:
    active: true
    threshold: 4
  ComplexCondition:
    threshold: 5

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    excludeGuardClauses: true
    max: 5
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 3
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  UnusedPrivateProperty:
    allowedNames: '_|ignored|expected|serialVersionUID|.+Handler'
