name: Build

on:
  push:
    branches: [ nextgen ]
  pull_request:
    branches: [ nextgen ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Grant all permissions for theme
        run: sudo chmod -R 777 theme
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk16
          arguments: genSources build
          gradle-version: wrapper
      - name: Upload artifact
        run: |
          cd build/libs
          export LB_VERSION=$(find . -regex '.*liquidbounce-[0-9|.]*\.jar')
          cp $LB_VERSION liquidbounce.jar
          curl --connect-timeout 30 -m 300 -X POST -F "artifact=@liquidbounce.jar" -H "Authentication: ${{ secrets.NIGHTLY_PASS }}" -F "gh_id=${{ github.event.head_commit.id }}" -F "gh_ref=${{ github.ref }}" -F "gh_message=${{ github.event.head_commit.message }}" -F "gh_timestamp=${{ github.event.head_commit.timestamp }}" -F "lb_version=$LB_VERSION" https://liquidbounce.net/php/nightly/webhook
